import re

with open('src/services/bracketService.js', 'r') as f:
    content = f.read()

# 1
content = content.replace(
    "      s.innerHTML = formatInlineToHtml(val)\n    }\n  })",
    "      s.innerHTML = formatInlineToHtml(val)\n" +
    "      if (s.getAttribute('data-var-inverse') === 'true') {\n" +
    "        const inverseIdx = (selectedIndex + 1) % choices.length\n" +
    "        s.innerHTML = formatInlineToHtml(choices[inverseIdx] ?? '')\n" +
    "      }\n" +
    "    }\n  })"
)

# 2. find the exact varDefs loop
var_defs_old = """  if (varDefs.length) {
    varDefs.forEach((v) => {
      const token = `$${v.name}$`
      const display = v.choices[v.selected] ?? ''
      const dataChoices = encodeURIComponent(JSON.stringify(v.choices || []))
      const spanHtml = `<span class="bracket-var" contenteditable="false" data-var-id="${v.id}" data-var-name="${escapeHtml(v.name)}" data-var-choices="${dataChoices}">${formatInlineToHtml(display)}</span>`
      // We only replace if it's NOT inside a tag (simple replace might be dangerous if $name$ is in attribute)
      // But $name$ is unlikely to be in attribute generated by us, except data-var-name.
      // We should be careful.
      // The original code did a global replace on `finalHtml`.
      finalHtml = finalHtml.replace(new RegExp(escapeRegex(token), 'g'), spanHtml)
    })
  }"""

var_defs_new = """  if (varDefs.length) {
    varDefs.forEach((v) => {
      if (v.choices && v.choices.length > 0) {
        const inverseIdx = (v.selected + 1) % v.choices.length
        const inverseDisplay = v.choices[inverseIdx] ?? ''
        const dataChoices = encodeURIComponent(JSON.stringify(v.choices || []))
        const inverseSpanHtml = `<span class="bracket-var bracket-var-inverse" contenteditable="false" data-var-id="${v.id}" data-var-name="${escapeHtml(v.name)}" data-var-choices="${dataChoices}" data-var-inverse="true">${formatInlineToHtml(inverseDisplay)}</span>`
        finalHtml = finalHtml.replace(new RegExp(escapeRegex(`$^${v.name}$`), 'g'), inverseSpanHtml)
      }

      const token = `$${v.name}$`
      const display = v.choices[v.selected] ?? ''
      const dataChoices = encodeURIComponent(JSON.stringify(v.choices || []))
      const spanHtml = `<span class="bracket-var" contenteditable="false" data-var-id="${v.id}" data-var-name="${escapeHtml(v.name)}" data-var-choices="${dataChoices}">${formatInlineToHtml(display)}</span>`
      finalHtml = finalHtml.replace(new RegExp(escapeRegex(token), 'g'), spanHtml)
    })
  }"""

content = content.replace(var_defs_old, var_defs_new)

old_walk = """  // walk text nodes and replace occurrences
  const walker = document.createTreeWalker(containerEl, NodeFilter.SHOW_TEXT, null)
  const toProcess = []
  let node
  while ((node = walker.nextNode())) {
    toProcess.push(node)
  }

  toProcess.forEach((textNode) => {
    let text = textNode.nodeValue
    if (!text) return
    // check for any token in the text
    Object.keys(map).forEach((name) => {
      const token = `$${name}$`
      if (text.includes(token)) {
        // split by token and build nodes
        const parts = text.split(token)
        const frag = document.createDocumentFragment()
        parts.forEach((part, idx) => {
          if (part) frag.appendChild(document.createTextNode(part))
          if (idx !== parts.length - 1) {
            const def = map[name]
            const span = document.createElement('span')
            span.className = 'bracket-var'
            span.setAttribute('contenteditable', 'false')
            span.setAttribute('data-var-id', def.id)
            span.setAttribute('data-var-name', def.name)
            span.setAttribute('data-var-choices', encodeURIComponent(JSON.stringify(def.choices || [])))
            span.innerHTML = formatInlineToHtml(def.choices[def.selected] ?? '')
            frag.appendChild(span)
          }
        })
        // guard against detached text nodes (parentNode may be null if DOM changed)
        if (!textNode.parentNode) return
        textNode.parentNode.replaceChild(frag, textNode)
      }
    })
  })"""

new_walk = """  function processTokens(prefix, isInverse) {
    const walker = document.createTreeWalker(containerEl, NodeFilter.SHOW_TEXT, null)
    const toProcess = []
    let node
    while ((node = walker.nextNode())) {
      toProcess.push(node)
    }

    toProcess.forEach((textNode) => {
      let text = textNode.nodeValue
      if (!text) return
      Object.keys(map).forEach((name) => {
        const token = prefix.replace('VARNAME', name)
        if (text.includes(token)) {
          const parts = text.split(token)
          const frag = document.createDocumentFragment()
          parts.forEach((part, idx) => {
            if (part) frag.appendChild(document.createTextNode(part))
            if (idx !== parts.length - 1) {
              const def = map[name]
              const span = document.createElement('span')
              span.className = isInverse ? 'bracket-var bracket-var-inverse' : 'bracket-var'
              span.setAttribute('contenteditable', 'false')
              span.setAttribute('data-var-id', def.id)
              span.setAttribute('data-var-name', def.name)
              span.setAttribute('data-var-choices', encodeURIComponent(JSON.stringify(def.choices || [])))
              if (isInverse) {
                 span.setAttribute('data-var-inverse', 'true')
                 const inverseIdx = (def.selected + 1) % def.choices.length
                 span.innerHTML = formatInlineToHtml(def.choices[inverseIdx] ?? '')
              } else {
                 span.innerHTML = formatInlineToHtml(def.choices[def.selected] ?? '')
              }
              frag.appendChild(span)
            }
          })
          if (!textNode.parentNode) return
          textNode.parentNode.replaceChild(frag, textNode)
          text = '' // clear text so we don't double replace the same old string
        }
      })
    })
  }

  processTokens('$^VARNAME$', true)
  processTokens('$VARNAME$', false)"""
content = content.replace(old_walk, new_walk)

with open('src/services/bracketService.js', 'w') as f:
    f.write(content)
