import fs from 'fs';
let content = fs.readFileSync('src/services/bracketService.js', 'utf8');

// 1. applyVarChoiceInDom (exactly 1 replacement)
content = content.replace(
  "      s.innerHTML = formatInlineToHtml(val)\n    }\n  })",
  "      s.innerHTML = formatInlineToHtml(val)\n" +
  "      if (s.getAttribute('data-var-inverse') === 'true') {\n" +
  "        const inverseIdx = (selectedIndex + 1) % choices.length\n" +
  "        s.innerHTML = formatInlineToHtml(choices[inverseIdx] ?? '')\n" +
  "      }\n" +
  "    }\n  })"
);

// 2. parseBracketsToHtml
// Find the exact block we want to replace
const varDefRegex = /  if \(varDefs\.length\) {\n    varDefs\.forEach\(\(v\) => {\n      const token = `\$\$\{v\.name\}\$`\n      const display = v\.choices\[v\.selected\] \?\? ''\n      const dataChoices = encodeURIComponent\(JSON\.stringify\(v\.choices \|\| \[\]\)\)\n      const spanHtml = `<span class="bracket-var" contenteditable="false" data-var-id="\$\{v\.id\}" data-var-name="\$\{escapeHtml\(v\.name\)\}" data-var-choices="\$\{dataChoices\}">\$\{formatInlineToHtml\(display\)\}<\/span>`\n      \/\/ We only replace if it's NOT inside a tag \(simple replace might be dangerous if \$name\$ is in attribute\)\n      \/\/ But \$name\$ is unlikely to be in attribute generated by us, except data-var-name\.\n      \/\/ We should be careful\.\n      \/\/ The original code did a global replace on `finalHtml`\.\n      finalHtml = finalHtml\.replace\(new RegExp\(escapeRegex\(token\), 'g'\), spanHtml\)\n    }\)\n  }/;

const varDefReplacement = `  if (varDefs.length) {
    varDefs.forEach((v) => {
      if (v.choices && v.choices.length > 0) {
        const inverseIdx = (v.selected + 1) % v.choices.length
        const inverseDisplay = v.choices[inverseIdx] ?? ''
        const dataChoices = encodeURIComponent(JSON.stringify(v.choices || []))
        const inverseSpanHtml = \`<span class="bracket-var bracket-var-inverse" contenteditable="false" data-var-id="\${v.id}" data-var-name="\${escapeHtml(v.name)}" data-var-choices="\${dataChoices}" data-var-inverse="true">\${formatInlineToHtml(inverseDisplay)}</span>\`
        finalHtml = finalHtml.replace(new RegExp(escapeRegex(\`$^\${v.name}$\`), 'g'), inverseSpanHtml)
      }

      const token = \`$\${v.name}$\`
      const display = v.choices[v.selected] ?? ''
      const dataChoices = encodeURIComponent(JSON.stringify(v.choices || []))
      const spanHtml = \`<span class="bracket-var" contenteditable="false" data-var-id="\${v.id}" data-var-name="\${escapeHtml(v.name)}" data-var-choices="\${dataChoices}">\${formatInlineToHtml(display)}</span>\`
      finalHtml = finalHtml.replace(new RegExp(escapeRegex(token), 'g'), spanHtml)
    })
  }`;

content = content.replace(varDefRegex, varDefReplacement);


// 3. replaceVarTokensInDom
const treeWalkerRegex = /  \/\/ walk text nodes and replace occurrences\n  const walker = document\.createTreeWalker\(containerEl, NodeFilter\.SHOW_TEXT, null\)\n  const toProcess = \[\]\n  let node\n  while \(\(node = walker\.nextNode\(\)\)\) {\n    toProcess\.push\(node\)\n  }\n\n  toProcess\.forEach\(\(textNode\) => {\n    let text = textNode\.nodeValue\n    if \(\!text\) return\n    \/\/ check for any token in the text\n    Object\.keys\(map\)\.forEach\(\(name\) => {\n      const token = `\$\$\{name\}\$`\n      if \(text\.includes\(token\)\) {\n        \/\/ split by token and build nodes\n        const parts = text\.split\(token\)\n        const frag = document\.createDocumentFragment\(\)\n        parts\.forEach\(\(part, idx\) => {\n          if \(part\) frag\.appendChild\(document\.createTextNode\(part\)\)\n          if \(idx \!== parts\.length - 1\) {\n            const def = map\[name\]\n            const span = document\.createElement\('span'\)\n            span\.className = 'bracket-var'\n            span\.setAttribute\('contenteditable', 'false'\)\n            span\.setAttribute\('data-var-id', def\.id\)\n            span\.setAttribute\('data-var-name', def\.name\)\n            span\.setAttribute\('data-var-choices', encodeURIComponent\(JSON\.stringify\(def\.choices \|\| \[\]\)\)\)\n            span\.innerHTML = formatInlineToHtml\(def\.choices\[def\.selected\] \?\? ''\)\n            frag\.appendChild\(span\)\n          }\n        }\)\n        \/\/ guard against detached text nodes \(parentNode may be null if DOM changed\)\n        if \(\!textNode\.parentNode\) return\n        textNode\.parentNode\.replaceChild\(frag, textNode\)\n      }\n    }\)\n  }\)/;

const treeWalkerReplacement = `  function processTokens(prefix, isInverse) {
    const walker = document.createTreeWalker(containerEl, NodeFilter.SHOW_TEXT, null)
    const toProcess = []
    let node
    while ((node = walker.nextNode())) {
      toProcess.push(node)
    }

    toProcess.forEach((textNode) => {
      let text = textNode.nodeValue
      if (!text) return
      Object.keys(map).forEach((name) => {
        const token = prefix.replace('{name}', name)
        if (text.includes(token)) {
          const parts = text.split(token)
          const frag = document.createDocumentFragment()
          parts.forEach((part, idx) => {
            if (part) frag.appendChild(document.createTextNode(part))
            if (idx !== parts.length - 1) {
              const def = map[name]
              const span = document.createElement('span')
              span.className = isInverse ? 'bracket-var bracket-var-inverse' : 'bracket-var'
              span.setAttribute('contenteditable', 'false')
              span.setAttribute('data-var-id', def.id)
              span.setAttribute('data-var-name', def.name)
              span.setAttribute('data-var-choices', encodeURIComponent(JSON.stringify(def.choices || [])))
              if (isInverse) {
                 span.setAttribute('data-var-inverse', 'true')
                 const inverseIdx = (def.selected + 1) % def.choices.length
                 span.innerHTML = formatInlineToHtml(def.choices[inverseIdx] ?? '')
              } else {
                 span.innerHTML = formatInlineToHtml(def.choices[def.selected] ?? '')
              }
              frag.appendChild(span)
            }
          })
          if (!textNode.parentNode) return
          textNode.parentNode.replaceChild(frag, textNode)
          text = '' // clear text so we don't double replace the same old string
        }
      })
    })
  }

  processTokens('$^' + '{name}' + '$', true)
  processTokens('$' + '{name}' + '$', false)`;

content = content.replace(treeWalkerRegex, treeWalkerReplacement);

fs.writeFileSync('src/services/bracketService.js', content, 'utf8');
