import { ref } from 'vue'

const STORAGE_KEY = 'protocol_language'

function safeReadLanguage() {
    if (typeof window === 'undefined' || !window.localStorage) return null
    try {
        return window.localStorage.getItem(STORAGE_KEY)
    } catch (err) {
        console.warn('Unable to read stored language', err)
        return null
    }
}

function safeWriteLanguage(lang) {
    if (typeof window === 'undefined' || !window.localStorage) return
    try {
        window.localStorage.setItem(STORAGE_KEY, lang)
    } catch (err) {
        console.warn('Unable to persist language preference', err)
    }
}

const languageOptions = [
    { code: 'vi', label: 'Tiếng Việt', flag: '🇻🇳' },
    { code: 'en', label: 'English', flag: '🇺🇸' }
]

const initialLang = (() => {
    const stored = safeReadLanguage()
    if (stored && ['vi', 'en'].includes(stored)) return stored
    return 'vi'
})()

const currentLang = ref(initialLang)

const translations = {
    vi: {
        selectProtocol: 'Chọn một phác đồ để xem hoặc chỉnh sửa',
        resetTooltip: 'Đặt lại phiên bản này về mặc định — nhấp để mở xác nhận',
        toggleFullscreen: 'Chuyển đổi toàn màn hình (Ctrl+Shift+F)',
        confirmResetTitle: 'Xác nhận đặt lại',
        confirmResetMessage: 'Đặt lại phác đồ này về nội dung mặc định ban đầu? Hành động này không thể hoàn tác.',
        reset: 'Đặt lại',
        cancel: 'Hủy',
        show: 'Hiện',
        hide: 'Không hiện',
        copy: 'Sao chép',
        copySource: 'Sao chép mã nguồn',
        copied: 'Đã sao chép',
        copyError: 'Lỗi sao chép',
        sourceCopied: 'Đã sao chép mã nguồn',
        protocolCopiedToast: 'Đã sao chép phác đồ vào bộ nhớ tạm',
        sourceCopiedToast: 'Đã sao chép mã nguồn phác đồ vào bộ nhớ tạm',
        unsavedDraft: '(bản nháp chưa lưu)',
        resetToDefault: 'Đã đặt lại về mặc định',
        searchPlaceholder: 'Tìm kiếm (Dấu phẩy = VÀ, e.g. giáp, thùy)',
        refreshProtocols: 'Làm mới danh sách phác đồ',
        openSpreadsheet: 'Mở bảng tính để chỉnh sửa',
        settings: 'Cài đặt',
        shortcuts: 'Phím tắt',
        settingsTitle: 'Cài đặt nguồn dữ liệu',
        downloadUrl: 'URL tải xuống (XLSX)',
        editUrl: 'URL chỉnh sửa bảng tính',
        open: 'Mở',
        saveAndLoad: 'Lưu & Tải',
        settingsTip: 'Mẹo: nhấp vào trường URL để chọn tất cả văn bản để sao chép dễ dàng.',
        language: 'Ngôn ngữ',
        vietnamese: 'Tiếng Việt',
        english: 'Tiếng Anh',
        menuFile: 'Tập tin',
        menuEdit: 'Chỉnh sửa',
        menuTools: 'Công cụ',
        menuHelp: 'Trợ giúp',
        menuFileRefresh: 'Làm mới dữ liệu',
        menuFileRefreshDesc: 'Tải lại toàn bộ danh sách phác đồ',
        menuFileGoogleSheet: 'Sửa đường dẫn Google Sheet',
        menuFileGoogleSheetDesc: 'Mở cài đặt nguồn dữ liệu',
        menuFileEditSheet: 'Sửa file Google Sheet',
        menuFileEditSheetDesc: 'Mở bảng tính Google Sheet trong tab mới',
        menuFileNewDesign: 'Thiết kế mới',
        menuFileNewDesignDesc: 'Tính năng sẽ bổ sung sau',
        menuEditCopy: 'Sao chép',
        menuEditCopyDesc: 'Sao chép phác đồ đang xem',
        menuEditCopySource: 'Sao chép mã nguồn',
        menuEditCopySourceDesc: 'Sao chép mã nguồn phác đồ dạng thô',
        menuEditResetAll: 'Reset toàn bộ nội dung',
        menuEditResetAllDesc: 'Xóa dữ liệu lưu cục bộ và tải lại',
        menuToolsLanguage: 'Ngôn ngữ',
        menuToolsLanguageDesc: 'Chọn ngôn ngữ giao diện',
        menuToolsFontSize: 'Kích thước chữ',
        menuToolsFontSizeDesc: 'Điều chỉnh kích thước chữ toàn hệ thống',
        menuHelpGuide: 'Hướng dẫn sử dụng',
        menuHelpGuideDesc: 'Mở tài liệu hướng dẫn',
        menuHelpShortcuts: 'Phím tắt',
        menuHelpShortcutsDesc: 'Xem bảng phím tắt hiện có',
        menuHelpAuthor: 'Thông tin tác giả',
        menuHelpAuthorDesc: 'Giới thiệu về bác sĩ Trần Quốc Hoài',
        close: 'Đóng',
        shortcutCopy: 'Sao chép phác đồ hiện tại (khi không có văn bản nào được chọn)',
        shortcutCopySource: 'Sao chép mã nguồn phác đồ (văn bản nguồn thô)',
        shortcutFullscreen: 'Chuyển đổi chế độ toàn màn hình cho trình soạn thảo',
        shortcutReset: 'Nút đặt lại từng phiên bản: Nhấp để mở hộp thoại xác nhận',
        shortcutNote: 'Lưu ý: Nếu bạn cập nhật bất kỳ phím tắt nào, hãy cập nhật thành phần này để giữ cho văn bản trợ giúp được đồng bộ.',
        loadingMessage: 'Đang tải phác đồ và phân tích nội dung…',
        generalSettings: 'Cài đặt chung',
        dataSettings: 'Dữ liệu',
        dangerZone: 'Vùng nguy hiểm',
        clearAllDrafts: 'Xóa toàn bộ bản nháp',
        clearAllDraftsDescription: 'Xóa tất cả các bản nháp đang chỉnh sửa. Các cài đặt và dữ liệu gốc sẽ được giữ nguyên.',
        confirmClearDraftsTitle: 'Xác nhận xóa bản nháp',
        confirmClearDraftsMessage: 'Bạn có chắc chắn muốn xóa toàn bộ các bản nháp đã lưu? Hành động này không thể hoàn tác.',
        fontSizeDialogTitle: 'Kích thước chữ',
        fontSizeSampleLabel: 'Số và text drquochoai',
        fontSizePresetSmall: 'Nhỏ',
        fontSizePresetMedium: 'Vừa',
        fontSizePresetLarge: 'Lớn',
        fontSizeHint: 'Điều chỉnh thanh trượt hoặc chọn nhanh để áp dụng ngay.',
        languageDialogTitle: 'Chọn ngôn ngữ hiển thị',
        languageDialogDescription: 'Thay đổi sẽ áp dụng ngay cho toàn bộ phần mềm.',
        authorDialogTitle: 'Thông tin tác giả',
        authorDialogDescription: 'Bác sĩ Trần Quốc Hoài — chuyên gia phẫu thuật lồng ngực và là chủ sở hữu nội dung.',
        authorDialogSummary: 'BS.CKI. Trần Quốc Hoài hiện công tác tại Trung tâm Ngoại Lồng ngực - Mạch máu, Bệnh viện Đa khoa Tâm Anh TP.HCM; tập trung điều trị các bệnh lý tim mạch, lồng ngực, tuyến giáp và mạch máu, đồng thời nghiên cứu tích cực ứng dụng công nghệ và AI vào chăm sóc bệnh nhân.',
        authorDialogSpecialtiesTitle: 'Chuyên môn chính',
        authorDialogSpecialtySurgery: 'Phẫu thuật tim mạch - lồng ngực, phẫu thuật tuyến giáp và xử trí cấp cứu mạch máu.',
        authorDialogSpecialtyVascular: 'Can thiệp nội mạch, tạo AVF, điều trị suy giãn tĩnh mạch và phình mạch chủ.',
        authorDialogSpecialtyInnovation: 'Nghiên cứu, ứng dụng trí tuệ nhân tạo và công nghệ số trong chẩn đoán, điều trị.',
        authorDialogContactTitle: 'Liên hệ trực tiếp',
        authorDialogContactLocation: 'Trung tâm Ngoại Lồng ngực - Mạch máu, Bệnh viện Đa khoa Tâm Anh TP.HCM.',
        authorDialogPhoneLabel: 'Điện thoại/Zalo',
        authorDialogEmailLabel: 'Email',
        authorDialogContactButton: 'Xem chi tiết & liên hệ',
        helpLinkComingSoon: 'Liên kết hướng dẫn sẽ được bổ sung sau.',
        comingSoon: 'Tính năng đang được phát triển.',
        draftsClearedToast: 'Đã xóa bộ nhớ tạm, ứng dụng sẽ tải lại.',
        appResetConfirmTitle: 'Reset toàn bộ dữ liệu',
        appResetConfirmMessage: 'Xóa tất cả dữ liệu lưu cục bộ (nguồn, bản nháp, cài đặt) và tải lại ứng dụng?',
        appResetAction: 'Reset ngay',
        appResetToast: 'Đã reset dữ liệu, đang tải lại...',
        languageUpdatedToast: 'Đã cập nhật ngôn ngữ.',
        fontSizeUpdatedToast: 'Đã cập nhật kích thước chữ.',
        authorDialogButton: 'Đóng',
        versionTitle: 'Tên phiên bản',
        pushToSheet: 'Đẩy lên Sheet',
        pushVersion: 'Đẩy bản nháp lên Google Sheet',
        pushNewVersion: 'Tạo cột mới',
        pushOverwrite: 'Ghi đè cột cũ',
        pushSuccess: 'Đã đẩy dữ liệu thành công',
        pushError: 'Có lỗi xảy ra khi đẩy dữ liệu',
        appScriptUrl: 'Google Apps Script URL',
        appScriptUrlMissing: 'Vui lòng cấu hình Google Apps Script URL trong phần Cài đặt.',
        pushDialogTitle: 'Đẩy (Push) Bản Nháp',
        pushDialogDesc: 'Nội dung chỉnh sửa sẽ được gửi lên Google Sheet dưới dạng một phiên bản mới hoặc ghi đè phiên bản cũ.',
        pushDialogTitleInput: 'Tên phiên bản (tùy chọn)',
        pushDialogMode: 'Chế độ',
        pushDialogModeNew: 'Tạo cột mới',
        pushDialogModeOverwrite: 'Ghi đè cột cũ',
        pushing: 'Đang xử lý...'
    },
    en: {
        selectProtocol: 'Select a protocol to view or edit',
        resetTooltip: 'Reset this version to default — click to open confirmation',
        toggleFullscreen: 'Toggle full screen (Ctrl+Shift+F)',
        confirmResetTitle: 'Confirm reset',
        confirmResetMessage: 'Reset this protocol to its original default content? This cannot be undone.',
        reset: 'Reset',
        cancel: 'Cancel',
        show: 'Show',
        hide: 'Hide',
        copy: 'Copy',
        copySource: 'Copy source',
        copied: 'Copied',
        copyError: 'Copy error',
        sourceCopied: 'Source copied',
        protocolCopiedToast: 'Protocol copied to clipboard',
        sourceCopiedToast: 'Protocol source copied to clipboard',
        unsavedDraft: '(unsaved draft)',
        resetToDefault: 'Reset to default',
        searchPlaceholder: 'Search (Comma = AND, e.g. thyroid, lobe)',
        refreshProtocols: 'Refresh protocols',
        openSpreadsheet: 'Open spreadsheet for edit',
        settings: 'Settings',
        shortcuts: 'Shortcuts',
        settingsTitle: 'Protocol source settings',
        downloadUrl: 'Download (XLSX) URL',
        editUrl: 'Edit spreadsheet URL',
        open: 'Open',
        saveAndLoad: 'Save & Load',
        settingsTip: 'Tip: click the URL field to select all text for easy copying.',
        language: 'Language',
        vietnamese: 'Vietnamese',
        english: 'English',
        menuFile: 'File',
        menuEdit: 'Edit',
        menuTools: 'Tools',
        menuHelp: 'Help',
        menuFileRefresh: 'Refresh data',
        menuFileRefreshDesc: 'Reload the full protocol list',
        menuFileGoogleSheet: 'Edit Google Sheet link',
        menuFileGoogleSheetDesc: 'Open data-source settings',
        menuFileEditSheet: 'Edit Google Sheet',
        menuFileEditSheetDesc: 'Open spreadsheet in a new tab',
        menuFileNewDesign: 'New design',
        menuFileNewDesignDesc: 'Coming soon',
        menuEditCopy: 'Copy',
        menuEditCopyDesc: 'Copy the currently displayed protocol',
        menuEditCopySource: 'Copy source',
        menuEditCopySourceDesc: 'Copy the raw protocol source text',
        menuEditResetAll: 'Hard reset all content',
        menuEditResetAllDesc: 'Clear local data and reload',
        menuToolsLanguage: 'Language',
        menuToolsLanguageDesc: 'Choose interface language',
        menuToolsFontSize: 'Font size',
        menuToolsFontSizeDesc: 'Adjust global font size',
        menuHelpGuide: 'User guide',
        menuHelpGuideDesc: 'Open documentation',
        menuHelpShortcuts: 'Hotkeys',
        menuHelpShortcutsDesc: 'Show keyboard shortcuts',
        menuHelpAuthor: 'About the author',
        menuHelpAuthorDesc: 'Details about Dr. Tran Quoc Hoai',
        close: 'Close',
        shortcutCopy: 'Copy current protocol (when no text is selected)',
        shortcutCopySource: 'Copy protocol source (raw source text)',
        shortcutFullscreen: 'Toggle full screen mode for editor',
        shortcutReset: 'Reset button: Click to open confirmation dialog for the current version',
        shortcutNote: 'Note: If you update any shortcuts, update this component to keep the help text in sync.',
        loadingMessage: 'Loading protocols and parsing content…',
        generalSettings: 'General Settings',
        dataSettings: 'Data',
        dangerZone: 'Danger Zone',
        clearAllDrafts: 'Clear All Drafts',
        clearAllDraftsDescription: 'Delete all saved drafts. Settings and original data will be preserved.',
        confirmClearDraftsTitle: 'Confirm Clear Drafts',
        confirmClearDraftsMessage: 'Are you sure you want to delete all saved drafts? This action cannot be undone.',
        fontSizeDialogTitle: 'Font size',
        fontSizeSampleLabel: 'Number & text drquochoai',
        fontSizePresetSmall: 'Small',
        fontSizePresetMedium: 'Medium',
        fontSizePresetLarge: 'Large',
        fontSizeHint: 'Use the slider or quick presets to update instantly.',
        languageDialogTitle: 'Choose interface language',
        languageDialogDescription: 'Changes apply immediately across the app.',
        authorDialogTitle: 'About the author',
        authorDialogDescription: 'Dr. Tran Quoc Hoai — thoracic surgeon and owner of the content.',
        authorDialogSummary: 'Dr. Tran Quoc Hoai (Thoracic & Cardiovascular Surgery specialist) practices at Tam Anh General Hospital in Ho Chi Minh City, focusing on thoracic, cardiovascular, thyroid, and vascular procedures while actively applying technology and AI to patient care.',
        authorDialogSpecialtiesTitle: 'Key expertise',
        authorDialogSpecialtySurgery: 'Cardiothoracic surgery, thyroid surgery, and vascular emergency management.',
        authorDialogSpecialtyVascular: 'Endovascular interventions, AVF creation, venous insufficiency treatment, aortic aneurysm repair.',
        authorDialogSpecialtyInnovation: 'Researching and deploying AI-driven and digital tools to enhance diagnostics and treatment.',
        authorDialogContactTitle: 'Direct contact',
        authorDialogContactLocation: 'Cardiothoracic Department, Tam Anh General Hospital (Ho Chi Minh City).',
        authorDialogPhoneLabel: 'Phone/Zalo',
        authorDialogEmailLabel: 'Email',
        authorDialogContactButton: 'View profile & contact',
        helpLinkComingSoon: 'The help link will be provided soon.',
        comingSoon: 'Feature coming soon.',
        draftsClearedToast: 'Temporary data cleared. Reloading...',
        appResetConfirmTitle: 'Reset all local data',
        appResetConfirmMessage: 'Remove every locally stored setting (sources, drafts, config) and reload the app?',
        appResetAction: 'Reset now',
        appResetToast: 'All local data cleared. Reloading...',
        languageUpdatedToast: 'Language updated.',
        fontSizeUpdatedToast: 'Font size updated.',
        authorDialogButton: 'Close',
        versionTitle: 'Version title',
        pushToSheet: 'Push to Sheet',
        pushVersion: 'Push draft to Google Sheet',
        pushNewVersion: 'Create new column',
        pushOverwrite: 'Overwrite original',
        pushSuccess: 'Pushed data successfully',
        pushError: 'An error occurred while pushing data',
        appScriptUrl: 'Google Apps Script URL',
        appScriptUrlMissing: 'Please configure Google Apps Script URL in Settings.',
        pushDialogTitle: 'Push Draft',
        pushDialogDesc: 'The edited content will be sent to Google Sheet as a new version or overwriting the old one.',
        pushDialogTitleInput: 'Version Title (Optional)',
        pushDialogMode: 'Mode',
        pushDialogModeNew: 'Create new column',
        pushDialogModeOverwrite: 'Overwrite original',
        pushing: 'Pushing...'
    }
};

function setLanguage(lang) {
    if (translations[lang]) {
        currentLang.value = lang
        safeWriteLanguage(lang)
    }
}

function t(key) {
    return translations[currentLang.value][key] || key
}

export default {
    currentLang,
    setLanguage,
    t,
    languageOptions
}
